### ISSUE TITLE
Github.com-en ez dabil

### ISSUE THREAD

**Issue by aldatsa** [iametza/datraolat#4]

**Comment by aldatsa** [comment]
@aldatsa​k f159ac57a6dd19f05686e44a3366c1c19d30f4af​rekin #4​a konpondu duela uste du​.
Normalean ez dut nire buruari buruz 3. pertsonan hitz egiten, funtzionatzen duen probatzeko da ;)

**Comment by aldatsa** [comment]
Bertsio berria argitaratu aurretik nabigatzaile guztietan probatu!

**Comment by aldatsa** [comment]
Gitlab eta Bitbucket-en ere funtzionatzen du

**Comment by iolkoz-iametza** [comment]
Kaixo,

kanpoan egongo naiz azaroaren 30 arte. Bitartean, zerbait behar izanez gero, mantenua@iametza.eus helbidera idatzi.

Eskerrik asko
